import React from 'react';
import { Presentation, TrendingUp, ShieldAlert, BarChart3, Clock } from 'lucide-react';
import { ExecutiveCopilotService } from '@/features/autonomous/executive/executive-copilot.service';

export default async function BoardDashboard() {
  const brief = await ExecutiveCopilotService.generateExecutiveBrief();
  const kpis = brief.kpi_snapshot.metrics;

  return (
    <div className="min-h-screen bg-white text-neutral-900 p-12 font-sans max-w-7xl mx-auto">
      {/* Print-friendly Board Header */}
      <div className="mb-12 border-b-2 border-neutral-900 pb-8 flex items-end justify-between">
        <div>
          <div className="flex items-center gap-3 mb-2 text-neutral-500">
            <Presentation className="w-6 h-6" />
            <h1 className="text-sm font-bold uppercase tracking-widest">Board of Directors Reporting</h1>
          </div>
          <h2 className="text-4xl font-extrabold text-neutral-900 tracking-tight">Quarterly Performance & Risk Review</h2>
          <p className="text-base text-neutral-500 mt-2 font-mono">
            PERIOD: {new Date(brief.period.start).toISOString().split('T')[0]} TO {new Date(brief.period.end).toISOString().split('T')[0]} | GENERATED BY: BOARD COPILOT
          </p>
        </div>
        <div className="text-right">
          <img src="/logo-dark.svg" alt="Company Logo" className="h-12 w-auto mb-4 opacity-10" />
          <div className="text-sm font-mono text-neutral-500">CONFIDENTIAL — DO NOT DISTRIBUTE</div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-12">
        
        {/* Left Column: Financials & Autonomy */}
        <div className="space-y-12">
          
          <section>
            <h3 className="text-xl font-bold border-b border-neutral-200 pb-2 mb-6 flex items-center gap-2">
              <TrendingUp className="w-5 h-5" /> Financial Health
            </h3>
            <div className="grid grid-cols-2 gap-6">
              <div className="bg-neutral-50 p-6 border border-neutral-200">
                <div className="text-sm text-neutral-500 uppercase tracking-widest font-semibold mb-2">Annual Recurring Revenue</div>
                <div className="text-4xl font-mono font-bold text-neutral-900 mb-2">${(kpis.arr.value / 1000000).toFixed(2)}M</div>
                <div className="text-sm font-mono text-emerald-600 font-bold">▲ {kpis.arr.delta_7d} (30D)</div>
              </div>
              <div className="bg-neutral-50 p-6 border border-neutral-200">
                <div className="text-sm text-neutral-500 uppercase tracking-widest font-semibold mb-2">Net Revenue Retention</div>
                <div className="text-4xl font-mono font-bold text-neutral-900 mb-2">{(kpis.nrr.value * 100).toFixed(1)}%</div>
                <div className="text-sm font-mono text-emerald-600 font-bold">▲ +{(parseFloat(kpis.nrr.delta_7d)).toFixed(1)}% (30D)</div>
              </div>
            </div>
            <div className="mt-6 bg-neutral-50 p-6 border border-neutral-200">
              <div className="text-sm text-neutral-500 uppercase tracking-widest font-semibold mb-4">30-Day Forward Projection</div>
              <div className="text-lg text-neutral-800 leading-relaxed">
                {brief.revenue_forecast_30d.narrative}
              </div>
            </div>
          </section>

          <section>
            <h3 className="text-xl font-bold border-b border-neutral-200 pb-2 mb-6 flex items-center gap-2">
              <BarChart3 className="w-5 h-5" /> Autonomous Operations
            </h3>
            <div className="bg-neutral-50 p-6 border border-neutral-200">
              <div className="grid grid-cols-3 gap-4 mb-6">
                <div>
                  <div className="text-xs text-neutral-500 uppercase font-semibold">Autonomy Score</div>
                  <div className="text-2xl font-mono font-bold text-neutral-900">{(kpis.autonomy_score.value * 100).toFixed(0)}%</div>
                </div>
                <div>
                  <div className="text-xs text-neutral-500 uppercase font-semibold">Resolution Rate</div>
                  <div className="text-2xl font-mono font-bold text-neutral-900">{(kpis.resolution_rate.value * 100).toFixed(0)}%</div>
                </div>
                <div>
                  <div className="text-xs text-neutral-500 uppercase font-semibold">Revenue Influenced</div>
                  <div className="text-2xl font-mono font-bold text-emerald-600">+${(brief.autonomy_snapshot.revenue_influenced_usd / 1000).toFixed(0)}K</div>
                </div>
              </div>
              <p className="text-sm text-neutral-600">
                Platform operations are increasingly handled by autonomous agents. {brief.autonomy_snapshot.autonomous_decisions_today.toLocaleString()} decisions were executed autonomously today, saving an estimated ${(brief.autonomy_snapshot.cost_saved_usd / 1000).toFixed(1)}K in operational costs MTD.
              </p>
            </div>
          </section>

        </div>

        {/* Right Column: Risks & Strategy */}
        <div className="space-y-12">
          
          <section>
            <h3 className="text-xl font-bold border-b border-neutral-200 pb-2 mb-6 flex items-center gap-2 text-red-600">
              <ShieldAlert className="w-5 h-5" /> Key Risks & Mitigations
            </h3>
            <div className="space-y-6">
              {brief.risks.map((risk, idx) => (
                <div key={idx} className="bg-white border-l-4 border-red-500 p-5 shadow-sm border border-neutral-200">
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="text-base font-bold text-neutral-900">{risk.description.split('—')[0]}</h4>
                    <span className="bg-red-100 text-red-700 text-xs font-bold px-2 py-1 uppercase rounded-sm">
                      IMPACT: {risk.impact_score}/5
                    </span>
                  </div>
                  <p className="text-sm text-neutral-600 mb-3">{risk.description.split('—')[1] || risk.description}</p>
                  <div className="bg-neutral-50 p-3 text-sm">
                    <span className="font-semibold text-neutral-700">Mitigation:</span> {risk.mitigation}
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h3 className="text-xl font-bold border-b border-neutral-200 pb-2 mb-6 flex items-center gap-2">
              <Clock className="w-5 h-5" /> Strategic Recommendations
            </h3>
            <div className="space-y-6">
              {brief.recommendations.map((rec, idx) => (
                <div key={idx} className="bg-neutral-50 border border-neutral-200 p-5">
                  <h4 className="text-base font-bold text-neutral-900 mb-2">{rec.title}</h4>
                  <p className="text-sm text-neutral-600 mb-4">{rec.description}</p>
                  <div className="flex gap-4 text-xs font-mono text-neutral-500 uppercase">
                    <span>OWNER: <strong className="text-neutral-900">{rec.suggested_owner}</strong></span>
                    <span>IMPACT: <strong className="text-emerald-600">+${(rec.expected_impact_usd! / 1000).toFixed(0)}K</strong></span>
                  </div>
                </div>
              ))}
            </div>
          </section>

        </div>
      </div>
    </div>
  );
}
